// WlTnc.idl : IDL source for WlTnc
//

// This file will be processed by the MIDL tool to
// produce the type library (WlTnc.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "customtnc.idl";


[
	uuid(94A1B6B7-B462-4F0E-A190-C3B92A966D90),
	version(1.0),
]
library WlTncLib
{
	importlib("stdole2.tlb");
	[
		uuid(785E8A35-3D60-4677-9F93-E572D921F320)
	]
	coclass WlTncA
	{
		[default] interface IWlTnc;
	};
};

import "shobjidl.idl";
