<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ImportGroup Label="PropertySheets">
    </ImportGroup>
    <PropertyGroup Label="UserMacros">
        <TncVersion1>1</TncVersion1>
        <TncVersion2>0</TncVersion2>
        <TncVersion3>1</TncVersion3>
        <TncVersion4>0</TncVersion4>
    </PropertyGroup>
    <ItemDefinitionGroup />
    <ItemGroup>
        <BuildMacro Include="TncVersion1">
            <Value>$(TncVersion1)</Value>
        </BuildMacro>
        <BuildMacro Include="TncVersion2">
            <Value>$(TncVersion2)</Value>
        </BuildMacro>
        <BuildMacro Include="TncVersion3">
            <Value>$(TncVersion3)</Value>
        </BuildMacro>
        <BuildMacro Include="TncVersion4">
            <Value>$(TncVersion4)</Value>
        </BuildMacro>
    </ItemGroup>
</Project>